# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': '\u7fa4\u7ec4', 'verbose_name_plural': '\u7fa4\u7ec4'},
        ),
    ]
